CREATE DATABASE employees ENCODING 'UTF-8';

CREATE TABLE IF NOT EXISTS EMPLOYEE(
    EMPID SERIAL PRIMARY KEY,
    EMPNAME VARCHAR(20),
    EMPSALARY INTEGER,
    EMPDEPT VARCHAR(20)
);

INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 20000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 30000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 40000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 50000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 60000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 70000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 80000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 90000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 10000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 25000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 35000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 45000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 55000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 65000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 75000, 'Dep 1');
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, EMPDEPT) VALUES (DEFAULT, 'Pavel', 85000, 'Dep 1');