CREATE DATABASE employees ENCODING 'UTF-8';

CREATE TABLE IF NOT EXISTS DEPARTMENT(
    DEPID SERIAL PRIMARY KEY,
    DEPNAME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE(
    EMPID SERIAL PRIMARY KEY,
    EMPNAME VARCHAR(20),
    EMPSALARY INTEGER,
    DEPID INTEGER REFERENCES DEPARTMENT (DEPID)
);

insert into DEPARTMENT (DEPID, DEPNAME) values (DEFAULT, 'Dep 1');
insert into DEPARTMENT (DEPID, DEPNAME) values (DEFAULT, 'Dep 2');
insert into DEPARTMENT (DEPID, DEPNAME) values (DEFAULT, 'Dep 3');

INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 20000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 30000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 40000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 50000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 60000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 70000, 1);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 80000, 2);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 90000, 2);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 10000, 2);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 25000, 2);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 35000, 3);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 45000, 3);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 55000, 3);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 65000, 3);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 75000, 3);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, EMPSALARY, DEPID) VALUES (DEFAULT, 'Pavel', 85000, 3);